### ISSUE TITLE
Phosh - Feature Request

### ISSUE THREAD

**Issue by mikeshenson** [dreemurrs-embedded/danctnix-tweaks#2]
I just updated my PinePhone with the latest image of the Arch with Phosh and found the tweaks app! This is GREAT! Thank you! Can you please add the removal of the "Show All Apps" button on the apps screen.

Now on to hiding the search bar!

OFF
gsettings set sm.puri.phosh app-filter-mode '[]'

ON
gsettings set sm.puri.phosh app-filter-mode '["adaptive"]'

![AdaptiveONOFF](https://user-images.githubusercontent.com/7337270/139518063-9c30636b-3157-4f45-a6dc-60fa33971aea.png)

**Comment by Danct12** [comment]
As this is a fork of postmarketOS Tweaks to adapt the branding, please report all the issue/feature enhancements on upstream: https://gitlab.com/postmarketOS/postmarketos-tweaks
